### PR TITLE
Fixed zerolog dependencies to point to github.com/rs/zerolog

### PR DESCRIPTION
**Pull request by sshumakov**
Changing zerolog reference to point to rs/zerolog as awishformore/zerolog fork is deleted.

### CODE REVIEW

**Comment by awishformore** [comment]
I fixed this in the branch I'm currently working on as well.
What your PR doesn't do is fix the `Gopkg.lock` file, which still has `awishformore/zerolog` as dependency instead of `rs/zerolog`.

**Comment by sshumakov** [comment]
Good point, need to run dep ensure.

**Comment by awishformore** [comment]
Somehow your version of `dep` changes the dependency file format, can you check you have the latest version?

**Comment by sshumakov** [comment]
My dep version is 0.4.1

**Pull request closed without merging**
